# Generated by Django 3.0.5 on 2020-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
